### ISSUE TITLE
select * from uptimerobot_monitor; doesn't list all monitors

### ISSUE THREAD

**Issue by prosinger** [turbot/steampipe-plugin-uptimerobot#12]
**Describe the bug**
it doesn't seem to list all the moniros when I do select all (no conditioning). It lists only 50, while we in fact have 177

**Steampipe version (`steampipe -v`)**
steampipe version 0.16.4

**Plugin version (`steampipe plugin list`)**
| hub.steampipe.io/plugins/turbot/uptimerobot@latest  | 0.0.1   | uptimerobot  |

**To reproduce**
select * from uptimerobot_monitor;

**Expected behavior**
to list all the motnitors there are

**Additional context**

**Comment by graza-io** [comment]
https://github.com/turbot/steampipe-plugin-uptimerobot/blob/f3efa7501456b8c2b1e9cccb06c1856b696904fa/uptimerobot/table_uptimerobot_monitor.go#L147

**Comment by cbruno10** [comment]
@prosinger @graza-io We have a PR open to address broken paging in this table and others. It'll be released later today!

**Comment by cbruno10** [comment]
@prosinger I've released a fix for this in v0.0.3, if you're still seeing issues, please re-open this issue and let us know.
